
DROP TABLE IF EXISTS LIBRARY;
CREATE TABLE LIBRARY (
LIB_ID INT   PRIMARY KEY,
LIB_NAME VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
BOOK_ID INT AUTO_INCREMENT  PRIMARY KEY,
LIB_ID INT (8) NOT NULL,
BOOK_NAME VARCHAR(50) NOT NULL,
BOOK_CATEGORY VARCHAR(50) NOT NULL,
BOOK_AUTHOR VARCHAR(50) NOT NULL
);
